const PLANS=[{id:'quartz',name:'Quartz',fee:500,points:30,maxClaims:30},{id:'amethyst',name:'Amethyst',fee:1000,points:40,maxClaims:50},{id:'garnet',name:'Garnet',fee:3000,points:110,maxClaims:50},{id:'aquamarine',name:'Aquamarine',fee:7000,points:240,maxClaims:50},{id:'sapphire',name:'Sapphire',fee:15000,points:500,maxClaims:50},{id:'emerald',name:'Emerald',fee:25000,points:858,maxClaims:50}];
const $=id=>document.getElementById(id);let token=localStorage.getItem('memberToken')||'';let member=null;let timer=null;
function apiUrl(){const u=window.APP_CONFIG&&window.APP_CONFIG.API_URL;if(!u||u.includes('PASTE_YOUR'))throw new Error('Set the Apps Script URL in config.js');return u}
async function api(action,payload={},auth=''){const r=await fetch(apiUrl(),{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,payload,token:auth})});const text=await r.text();let d;try{d=JSON.parse(text)}catch(e){throw new Error('Backend did not return JSON. Check the /exec URL and deployment access.')}if(!d.ok)throw new Error(d.error||'Request failed');return d.data}
function notice(m){$('notice').textContent=m;$('notice').classList.remove('hidden');setTimeout(()=>$('notice').classList.add('hidden'),5000)}
function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id).classList.add('active');if(id==='dashboard'&&token)loadDashboard()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));$('logoutBtn').onclick=()=>{token='';localStorage.removeItem('memberToken');updateNav();show('login')};
function plans(target,buttons=false){$(target).innerHTML=PLANS.map(p=>`<div class="card plan"><h3>${p.name}</h3><div class="price">₱${p.fee.toLocaleString()}</div><p>${p.points} points/day · ${p.maxClaims} claims</p>${buttons?`<button data-plan="${p.id}" class="buy">Activate</button>`:''}</div>`).join('');if(buttons)document.querySelectorAll('.buy').forEach(b=>b.onclick=()=>buy(b.dataset.plan))}plans('publicPlans');
$('registerForm').onsubmit=async e=>{e.preventDefault();try{await api('register',{fullName:$('regName').value.trim(),email:$('regEmail').value.trim().toLowerCase(),mobile:$('regMobile').value.trim(),password:$('regPassword').value});notice('Registration successful. Please log in.');e.target.reset();show('login')}catch(err){notice(err.message)}};
$('loginForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('login',{email:$('loginEmail').value.trim().toLowerCase(),password:$('loginPassword').value});token=d.token;localStorage.setItem('memberToken',token);updateNav();show('dashboard')}catch(err){notice(err.message)}};
$('depositForm').onsubmit=async e=>{e.preventDefault();try{await api('submitDeposit',{amount:Number($('depAmount').value),method:$('depMethod').value,reference:$('depReference').value.trim(),proofUrl:$('depProof').value.trim()},token);notice('Deposit submitted for approval.');e.target.reset();loadDashboard()}catch(err){notice(err.message)}};
$('claimBtn').onclick=async()=>{try{member=await api('claimPoints',{},token);render();notice('Points claimed.')}catch(err){notice(err.message)}};
async function buy(planId){const p=PLANS.find(x=>x.id===planId);if(!confirm(`Activate ${p.name} for ₱${p.fee}?`))return;try{member=await api('buyMembership',{planId},token);render();notice('Membership activated.')}catch(err){notice(err.message)}}
async function loadDashboard(){try{member=await api('memberDashboard',{},token);render()}catch(err){notice(err.message)}}
function render(){ $('wallet').textContent='₱'+Number(member.walletBalance).toLocaleString();$('points').textContent=Number(member.pointsBalance).toLocaleString();$('membership').textContent=member.membership?member.membership.planName:'None';$('status').textContent=member.membership?member.membership.status:'Inactive';plans('memberPlans',true);if(member.membership&&member.membership.status==='Active')document.querySelectorAll('.buy').forEach(b=>b.disabled=true);$('depositHistory').innerHTML=member.deposits.length?member.deposits.map(d=>`<div class="history"><span>${d.method} · ${d.reference}</span><strong>₱${Number(d.amount).toLocaleString()} · ${d.status}</strong></div>`).join(''):'No deposits yet.';$('claimHistory').innerHTML=member.claims.length?member.claims.map(c=>`<div class="history"><span>${new Date(c.claimedAt).toLocaleString()}</span><strong>+${c.points}</strong></div>`).join(''):'No claims yet.';startTimer()}
function startTimer(){clearInterval(timer);const tick=()=>{const m=member&&member.membership;if(!m){$('countdown').textContent='--:--:--';$('claimBtn').disabled=true;return}if(m.status==='Completed'){$('countdown').textContent='COMPLETED';$('claimBtn').disabled=true;return}const rem=Math.max(0,new Date(m.nextClaimAt)-Date.now());const h=Math.floor(rem/3600000),mi=Math.floor(rem%3600000/60000),s=Math.floor(rem%60000/1000);$('countdown').textContent=`${String(h).padStart(2,'0')}:${String(mi).padStart(2,'0')}:${String(s).padStart(2,'0')}`;$('claimBtn').disabled=rem>0;$('claimText').textContent=rem>0?'Countdown running.':'Ready to claim. Timer stays at zero until claimed.'};tick();timer=setInterval(tick,1000)}
function updateNav(){document.querySelectorAll('.member').forEach(x=>x.classList.toggle('hidden',!token));document.querySelectorAll('.guest').forEach(x=>x.classList.toggle('hidden',!!token))}updateNav();if(token)show('dashboard');
